baseurl = "https://osummer.github.io/"
languageCode = "zh-Hans"
title = "Osummer的空间"
theme = "simple-frame"

[permalinks]
  posts = "/post/:slug/"
  search = "/search/"

[Params]
  Subtitle = "Inspired by the nature."
  mainSections = ["post", "docs"]
  post_meta = ["date", "categories", "taglist"]
  dateformat = "2006-01-02"
  toc = true
  pager = true

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "categories", "taglist", "recent", "archives"]

[Params.widgets]
  recent_num = 5
  categories_counter = true
  tags_counter = true
  
[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[related]
  includeNewer = true
[[related.indices]]
  name = "tags"
  weight = 80
[[related.indices]]
  name = "categories"
  weight = 60
